# 와인분석 기본

In [88]:
import pandas as pd

## [실습1] 데이터 프레임 만들기

In [89]:

# 데이터에 인덱스 포함되어 있는경우, 인덱스 컬럼 제외하고 로딩하기
data_path = 'datas/winemag-data_first150k.csv'
df = pd.read_csv(data_path).iloc[:,1:]
df.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150930 entries, 0 to 150929
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   country      150925 non-null  str
 1   description  150930 non-null  str
 2   designation  105195 non-null  str
 3   points       150930 non-null  int64
 4   price        137235 non-null  float64
 5   province     150925 non-null  str
 6   region_1     125870 non-null  str
 7   region_2     60953 non-null   str
 8   variety      150930 non-null  str
 9   winery       150930 non-null  str
dtypes: float64(1), int64(1), str(8)
memory usage: 11.5 MB

- 주요 컬럼 : country(와인 생산 국가), description(리뷰) points(점수), price(가격), province(지방)

In [91]:
# 리뷰의 디스크립션 컬럼을 desc로 지정
dsec = df[['country','description','points','price','province']]
dsec.head(15)

,country,description,points,price,province
0,US,This tremendous 100% varietal wine hails from ...,96,235.0,California
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",96,110.0,Northern Spain
2,US,Mac Watson honors the memory of a wine once ma...,96,90.0,California
3,US,"This spent 20 months in 30% new French oak, an...",96,65.0,Oregon
4,France,"This is the top wine from La Bégude, named aft...",95,66.0,Provence
5,Spain,"Deep, dense and pure from the opening bell, th...",95,73.0,Northern Spain
6,Spain,Slightly gritty black-fruit aromas include a s...,95,65.0,Northern Spain
7,Spain,Lush cedary black-fruit aromas are luxe and of...,95,110.0,Northern Spain
8,US,This re-named vineyard was formerly bottled as...,95,65.0,Oregon
9,US,The producer sources from two blocks of the vi...,95,60.0,California
10,Italy,"Elegance, complexity and structure come togeth...",95,80.0,Northeastern Italy
11,US,"From 18-year-old vines, this supple well-balan...",95,48.0,Oregon
12,US,A standout even in this terrific lineup of 201...,95,48.0,Oregon
13,France,This wine is in peak condition. The tannins an...,95,90.0,Southwest France
14,US,"With its sophisticated mix of mineral, acid an...",95,185.0,Oregon

## [실습2] data access

- description 컬럼의 첫번째 데이터를, first_description 이라는 변수에 저장하기

In [92]:
# 방법1
first_description = df[['description']]
first_description.head()

                                         description
0  This tremendous 100% varietal wine hails from ...
1  Ripe aromas of fig, blackberry and cassis are ...
2  Mac Watson honors the memory of a wine once ma...
3  This spent 20 months in 30% new French oak, an...
4  This is the top wine from La Bégude, named aft...

- description column의 값들 중, 첫번재부터 10번째 데이터까지를 first_description 변수에 저장한다.

In [97]:
# loc() 방식
first_description = first_description.head(10)
first_description

                                         description
0  This tremendous 100% varietal wine hails from ...
1  Ripe aromas of fig, blackberry and cassis are ...
2  Mac Watson honors the memory of a wine once ma...
3  This spent 20 months in 30% new French oak, an...
4  This is the top wine from La Bégude, named aft...
5  Deep, dense and pure from the opening bell, th...
6  Slightly gritty black-fruit aromas include a s...
7  Lush cedary black-fruit aromas are luxe and of...
8  This re-named vineyard was formerly bottled as...
9  The producer sources from two blocks of the vi...

In [98]:
# iloc() 방식
first_description = first_description.iloc[:10]
first_description

                                         description
0  This tremendous 100% varietal wine hails from ...
1  Ripe aromas of fig, blackberry and cassis are ...
2  Mac Watson honors the memory of a wine once ma...
3  This spent 20 months in 30% new French oak, an...
4  This is the top wine from La Bégude, named aft...
5  Deep, dense and pure from the opening bell, th...
6  Slightly gritty black-fruit aromas include a s...
7  Lush cedary black-fruit aromas are luxe and of...
8  This re-named vineyard was formerly bottled as...
9  The producer sources from two blocks of the vi...

- 인덱스가 1,2,3,4,5,8 인 데이터를, sample_reviews 변수에 저장한다.

In [99]:
sample_reviews = 
sample_reviews

SyntaxError: invalid syntax (2877005276.py, line 1)

In [ ]:
# 인덱스가 0, 1, 10, 100인 데이터에서, 컬럼이 country, province, region_1, region_2인 데이터만 가져오기

    country            province     region_1     region_2
0        US          California  Napa Valley         Napa
1     Spain      Northern Spain         Toro          NaN
10    Italy  Northeastern Italy       Collio          NaN
100      US          California  South Coast  South Coast

## [실습3] 데이터 필터링 
- Italy 에서 만들어진 와인만 가져오기

In [ ]:
# nan 값 포함해서 유니크한 값 가져옴

array(['US', 'Spain', 'France', 'Italy', 'New Zealand', 'Bulgaria',
       'Argentina', 'Australia', 'Portugal', 'Israel', 'South Africa',
       'Greece', 'Chile', 'Morocco', 'Romania', 'Germany', 'Canada',
       'Moldova', 'Hungary', 'Austria', 'Croatia', 'Slovenia', nan,
       'India', 'Turkey', 'Macedonia', 'Lebanon', 'Serbia', 'Uruguay',
       'Switzerland', 'Albania', 'Bosnia and Herzegovina', 'Brazil',
       'Cyprus', 'Lithuania', 'Japan', 'China', 'South Korea', 'Ukraine',
       'England', 'Mexico', 'Georgia', 'Montenegro', 'Luxembourg',
       'Slovakia', 'Czech Republic', 'Egypt', 'Tunisia', 'US-France'],
      dtype=object)

49

In [ ]:
# unique한 값의 갯수, nan은 제외한 갯수 계산

48

In [ ]:
df.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

0         False
1         False
2         False
3         False
4         False
          ...
150925     True
150926    False
150927     True
150928    False
150929     True
Name: country, Length: 150930, dtype: bool

In [ ]:
# - Italy 에서 만들어진 와인만 가져오세요
# df.loc[행,열]

- 리뷰점수가 95점 이상이고, Australia 또는 New Zealand 에서 만들어진 와인 데이터를 가져오세요

In [ ]:
# 리뷰점수가 95점 이상이고, Australia 또는 New Zealand 에서 만들어진 와인 데이터를 가져오세요
# df.loc[행, 열]